
# kubectl create deployment sync-env --image akankshakumari393/node-label-controller:0.0.1

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-label-controller
  name: node-label-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-label-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: node-label-controller
    spec:
      containers:
      - image: akankshakumari393/node-label-controller:0.0.1
        name: node-label-controller
        args: ["linux"]
        #command: ["node-label-controller"]